import { Oswald } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const oswald = Oswald({ subsets: ["latin"] });

export const metadata = {
  title: "PlayPerk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <div className={oswald.className}>
          <Header />
          <div className="w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
